# These environment variables must be set in CircleCI UI
#
# DOCKER_EMAIL   - login info for docker hub
# DOCKER_USER
# DOCKER_PASS
#
# Read the README for more information.

version: 2
jobs:
  build:
    working_directory: /go/src/github.com/wowast/deployer
    docker:
      - image: circleci/golang:1.10

    dependencies:
      override:
        - rm -rf ${GOPATH_BASE}/
        - mkdir -p "$GOPATH_BASE"
        - mkdir -p "$GOPATH/bin"
        - cp -r ${HOME}/${CIRCLE_PROJECT_REPONAME} ${GOPATH_BASE}/
        - go get github.com/govend/govend
        - sudo pip install awscli

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment
          command: |
            gb="/src/github.com/${CIRCLE_PROJECT_USERNAME}";
            cat >> $BASH_ENV << EOF
            export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"
            export GOPATH_BASE="$(echo ${GOPATH}|cut -d ':' -f 1)${gb}"
            EOF

      - run:
          command:
            mkdir -p "${GOPATH_BASE}"
            mkdir -p "${GOPATH_HEAD}/bin"

      - run:
          name: Build application container
          command: |
            go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
            [ ! -e bin ] && mkdir bin;
            cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/deployer;
            chmod +x deploymentTests/*
            docker build -t wowast/${CIRCLE_PROJECT_REPONAME} .;
            GOPATH="$GOPATH_HEAD"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u && git diff --quiet )

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};

               docker images --no-trunc | awk '/^app/ {print $3}' | \
                 sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
               docker push wowast/${CIRCLE_PROJECT_REPONAME};

              # trigger ebs redeploy
              #      - aws elasticbeanstalk update-environment --region us-east-1 --application-name invoicer201707071231 --environment-id e-h4vyur8nup --version-label deployer-api

            fi